model:
    prediction_len: 10
    imu_input_size: 6
    imu_embed_size: 30
    imu_dropout: 0.3
    imu_hidden_size: 128
    image_embed_size: 30
    fusion_output_dim: 64
    fusion_hidden_size: 128
    fusion_dropout: 0.3
    decoder_hidden_size: 128
dataset:
    train_data:
        data_path: "data/vicon_room_1_easy/mav0"
        combined_csv_path: "data/vicon_room_1_easy/combined.csv"
        vio_csv_path: "data/vins_output/V1_01_easy.csv"
    test_data:
        data_path: "data/vicon_room_1_medium/mav0"
        combined_csv_path: "data/vicon_room_1_medium/combined.csv"
        vio_csv_path: "data/vins_output/V1_02_medium.csv"
    image_width: 96
    image_height: 96
    image_channels: 1
    seq_len: 5
    train_batch_size: 32
    val_batch_size:  16
    test_batch_size: 1
    num_workers: 4
trainer:
    max_epochs: 50
    LR: .001
    gpus: [0]
logging:
    save_dir: "logs/"
    name: "SLAMErrorPrediction"
    validation_output_file: "validation_output_gt.csv"
    testing_output_file: "testing_output_gt.csv"
experiment:
    weight_decay: .0001
    scheduler: "ExponentialLR"
    scheduler_gamma: 0.975
    step_size: 1
    manual_seed: 228
loss:
    name: MSELoss
    args:
        # Add args if needed